import { ArrowRight, CalendarDays, GitCompareArrows } from 'lucide-react';
import { usePortfolioContext } from '@/lib/portfolio-context';
import { EmptyState, ErrorState, LoadingState, SectionHeading, StatusPill } from '@/components/portfolio-ui';
import { formatDate } from '@/lib/portfolio';

export default function ChangeLog() {
  const { snapshot, loading, error, refresh } = usePortfolioContext();
  if (loading) return <LoadingState />;
  if (error || !snapshot) return <ErrorState onRetry={refresh} />;
  const entries = [...snapshot.changeLog].sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
  return <div className="stagger-in space-y-8"><section><p className="eyebrow text-muted-foreground">Audit / movement</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-0.04em] sm:text-4xl">Change log.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Newest first. A compact record of what changed, why it matters, and who touched the tracker.</p></section><div className="flex items-center gap-3 rounded-xl border border-border bg-card px-4 py-3 text-xs"><GitCompareArrows size={16} /><span><strong>{entries.length} tracked changes</strong> in the latest portfolio snapshot.</span></div><section><SectionHeading eyebrow="Newest first" title="Portfolio movement" /><div className="panel divide-y divide-border overflow-hidden rounded-2xl">{entries.map((entry, index) => <article className="grid gap-5 p-5 md:grid-cols-[150px_1fr_180px] md:gap-8" key={`${entry.timestamp}-${entry.project}-${index}`} data-testid={`change-log-entry-${index}`}><div className="flex items-start gap-2 text-xs text-muted-foreground"><CalendarDays size={14} className="mt-0.5 shrink-0" /><span>{formatDate(entry.timestamp, true)}</span></div><div><h3 className="text-sm font-extrabold">{entry.project}</h3><div className="mt-2 flex flex-wrap items-center gap-2"><StatusPill value={entry.previousStage} stage /><ArrowRight size={13} className="text-muted-foreground" /><StatusPill value={entry.newStage} stage /></div><p className="mt-3 text-xs leading-5 text-muted-foreground">{entry.evidence || entry.gateChange || 'No evidence note recorded.'}</p></div><div className="md:text-right"><p className="eyebrow text-muted-foreground">Updated by</p><p className="mt-1 text-xs font-bold">{entry.updatedBy || 'Unknown'}</p><p className="mt-4 text-[10px] text-muted-foreground">{entry.previousStatus} → {entry.newStatus}</p></div></article>)}{entries.length === 0 && <EmptyState title="No changes in this snapshot" description="The change log will populate as project stages and statuses move." />}</div></section></div>;
}