import { ArrowRight, CalendarClock, CircleAlert, Layers3, Radar, Workflow } from 'lucide-react';
import { Link } from 'wouter';
import { useMemo } from 'react';
import { usePortfolioContext } from '@/lib/portfolio-context';
import { ErrorState, LoadingState, ProjectCard, SectionHeading, StatCard, StatusPill } from '@/components/portfolio-ui';
import { formatDate, groupBy, relativeDate } from '@/lib/portfolio';

export default function Dashboard() {
  const { snapshot, loading, error, refresh } = usePortfolioContext();
  const projects = snapshot?.projects || [];
  const familyGroups = useMemo(() => groupBy(projects, (project) => project.portfolioFamily), [projects]);
  const stageGroups = useMemo(() => groupBy(projects, (project) => project.lifecycleStage), [projects]);
  const attention = projects.filter((project) => /waiting|blocked/i.test(project.status) || project.blocker);
  const nearBeta = projects.filter((project) => /beta|ready/i.test(`${project.betaStatus} ${project.launchStatus}`) || project.lifecycleStage.toLowerCase() === 'beta').slice(0, 4);
  const platformGroups = useMemo(() => groupBy(projects, (project) => project.currentWorkPlatform), [projects]);

  if (loading) return <LoadingState />;
  if (error || !snapshot) return <ErrorState onRetry={refresh} />;

  return <div className="stagger-in space-y-9">
    <section className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><p className="eyebrow text-muted-foreground">Tuesday / portfolio pulse</p><h1 className="mt-2 max-w-3xl text-3xl font-extrabold tracking-[-0.05em] sm:text-5xl">Build the right thing.<br /><span className="text-muted-foreground">At the right gate.</span></h1><p className="mt-4 max-w-xl text-sm leading-6 text-muted-foreground">A high-signal view across {projects.length} systems. Pick the next decision, then get back to making.</p></div><div className="flex items-center gap-3"><div className="rounded-xl border border-border bg-card px-4 py-3"><p className="eyebrow text-muted-foreground">Last sync</p><p className="mt-1 text-xs font-bold">{formatDate(snapshot.syncedAt, true)}</p></div><span className="hidden size-2 rounded-full bg-emerald-500 sm:block" /></div></section>
    {snapshot.warning && <div className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-900" data-testid="alert-sync-warning"><CircleAlert size={15} className="mt-0.5 shrink-0" /><span>{snapshot.warning}</span></div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Tracked projects" value={projects.length} detail={`${Object.keys(familyGroups).length} portfolio families`} /><StatCard label="Needs attention" value={attention.length} detail="Waiting, blocked, or with a blocker" accent={attention.length ? 'amber' : 'default'} /><StatCard label="In beta orbit" value={nearBeta.length} detail="Beta or launch readiness signals" accent="teal" /><StatCard label="Active platforms" value={Object.keys(platformGroups).length} detail="Distinct places work is happening" /></section>
    <section className="grid gap-7 xl:grid-cols-[1.18fr_.82fr]">
      <div><SectionHeading eyebrow="Signal / 01" title="Attention queue" description="Items where the next move depends on a clear decision." action={<Link href="/waiting" className="focus-ring inline-flex items-center gap-1 text-xs font-bold text-muted-foreground hover:text-foreground" data-testid="link-view-waiting">View waiting <ArrowRight size={14} /></Link>} /><div className="space-y-3">{attention.slice(0, 4).map((project) => <Link href={`/projects/${encodeURIComponent(project.projectId)}`} key={project.projectId} className="panel focus-ring flex items-center justify-between gap-4 rounded-xl p-4 transition hover:border-foreground/25" data-testid={`attention-${project.projectId}`}><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-extrabold">{project.project}</p><StatusPill value={project.status} /></div><p className="mt-2 truncate text-xs text-muted-foreground">{project.blocker || project.exactNextAction || 'No blocker recorded'}</p></div><div className="hidden shrink-0 text-right sm:block"><p className="eyebrow text-muted-foreground">Last touch</p><p className="mt-1 text-[11px] font-semibold">{relativeDate(project.lastActivity)}</p></div><ArrowRight size={15} className="shrink-0 text-muted-foreground sm:hidden" /></Link>)}{attention.length === 0 && <div className="panel rounded-xl p-7 text-center text-sm text-muted-foreground">No items are asking for an intervention.</div>}</div></div>
      <div><SectionHeading eyebrow="Portfolio shape" title="Lifecycle mix" /><div className="panel rounded-2xl p-5"><div className="space-y-4">{Object.entries(stageGroups).sort((a, b) => b[1].length - a[1].length).map(([stage, items]) => <div key={stage} data-testid={`lifecycle-${stage}`}><div className="mb-2 flex items-center justify-between text-xs"><span className="font-bold">{stage}</span><span className="font-mono-ui text-muted-foreground">{items.length} / {projects.length}</span></div><div className="h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-foreground" style={{ width: `${(items.length / projects.length) * 100}%` }} /></div></div>)}</div><div className="mt-6 grid grid-cols-2 gap-3 border-t border-border pt-5">{Object.entries(familyGroups).slice(0, 4).map(([family, items]) => <div key={family}><p className="truncate text-[11px] font-bold">{family}</p><p className="mt-1 font-mono-ui text-[10px] text-muted-foreground">{items.length} systems</p></div>)}</div></div></div>
    </section>
    <section><SectionHeading eyebrow="Signal / 02" title="Beta-near projects" description="The projects closest to a meaningful external test." action={<Link href="/beta-launch" className="focus-ring inline-flex items-center gap-1 text-xs font-bold text-muted-foreground hover:text-foreground" data-testid="link-view-beta">Readiness board <ArrowRight size={14} /></Link>} /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{nearBeta.map((project) => <ProjectCard key={project.projectId} project={project} compact />)}{nearBeta.length === 0 && <div className="col-span-full"><div className="panel rounded-xl p-8 text-center text-sm text-muted-foreground">Nothing is currently tagged for beta or launch.</div></div>}</div></section>
    <section className="grid gap-7 xl:grid-cols-[.8fr_1.2fr]"><div><SectionHeading eyebrow="Operating system" title="Work platform" /><div className="panel divide-y divide-border rounded-2xl">{Object.entries(platformGroups).sort((a, b) => b[1].length - a[1].length).map(([platform, items]) => <div className="flex items-center justify-between p-4" key={platform} data-testid={`platform-${platform}`}><div className="flex items-center gap-3"><div className="grid size-8 place-items-center rounded-lg bg-secondary"><Workflow size={15} /></div><span className="text-xs font-bold">{platform}</span></div><span className="font-mono-ui text-[11px] text-muted-foreground">{items.length} projects</span></div>)}</div></div><div><SectionHeading eyebrow="Portfolio families" title="Where attention is concentrated" /><div className="grid gap-3 sm:grid-cols-2">{Object.entries(familyGroups).map(([family, items]) => <Link href={`/portfolio?family=${encodeURIComponent(family)}`} className="panel focus-ring group rounded-xl p-4 transition hover:border-foreground/25" key={family} data-testid={`family-summary-${family}`}><div className="flex items-center justify-between"><div className="grid size-8 place-items-center rounded-lg bg-secondary"><Layers3 size={15} /></div><ArrowRight size={15} className="text-muted-foreground transition group-hover:translate-x-0.5 group-hover:text-foreground" /></div><p className="mt-4 text-sm font-extrabold">{family}</p><div className="mt-2 flex items-center justify-between text-[10px] text-muted-foreground"><span>{items.length} projects</span><span>{Math.round(items.reduce((sum, item) => sum + item.levelPercent, 0) / items.length)}% Avg Overall Project Progress</span></div></Link>)}</div></div></section>
    <div className="flex items-center justify-between border-t border-border pt-5 text-[11px] text-muted-foreground"><span className="flex items-center gap-2"><Radar size={14} /> Portfolio snapshot is {snapshot.mode.toLowerCase()}.</span><span className="flex items-center gap-2"><CalendarClock size={13} /> Updates are tracker-driven.</span></div>
  </div>;
}