import { ArrowDownAZ, ArrowUpAZ, Grid2X2, List, Search, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { usePortfolioContext } from '@/lib/portfolio-context';
import { EmptyState, ErrorState, LoadingState, ProjectCard, SectionHeading, StatusPill } from '@/components/portfolio-ui';
import { relativeDate, uniqueValues, type SortKey } from '@/lib/portfolio';

export default function Projects() {
  const { snapshot, loading, error, refresh } = usePortfolioContext();
  const [query, setQuery] = useState('');
  const [family, setFamily] = useState('All families');
  const [stage, setStage] = useState('All stages');
  const [status, setStatus] = useState('All statuses');
  const [sort, setSort] = useState<SortKey>('activity');
  const [ascending, setAscending] = useState(false);
  const [view, setView] = useState<'grid' | 'list'>('grid');
  const projects = snapshot?.projects || [];
  const families = uniqueValues(projects, 'portfolioFamily');
  const stages = uniqueValues(projects, 'lifecycleStage');
  const statuses = uniqueValues(projects, 'status');
  const filtered = useMemo(() => projects.filter((project) => {
    const haystack = `${project.project} ${project.projectId} ${project.portfolioFamily} ${project.category} ${project.exactNextAction}`.toLowerCase();
    return haystack.includes(query.toLowerCase()) && (family === 'All families' || project.portfolioFamily === family) && (stage === 'All stages' || project.lifecycleStage === stage) && (status === 'All statuses' || project.status === status);
  }).sort((a, b) => {
    const result = sort === 'level' ? a.levelPercent - b.levelPercent : sort === 'name' ? a.project.localeCompare(b.project) : sort === 'family' ? a.portfolioFamily.localeCompare(b.portfolioFamily) : new Date(a.lastActivity).getTime() - new Date(b.lastActivity).getTime();
    return ascending ? result : -result;
  }), [projects, query, family, stage, status, sort, ascending]);
  const clearFilters = () => { setQuery(''); setFamily('All families'); setStage('All stages'); setStatus('All statuses'); };
  if (loading) return <LoadingState />;
  if (error || !snapshot) return <ErrorState onRetry={refresh} />;
  return <div className="stagger-in space-y-7">
    <section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-muted-foreground">Portfolio / all projects</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-0.04em]">Every project. One working view.</h1><p className="mt-3 text-sm text-muted-foreground">{filtered.length} of {projects.length} projects currently visible.</p></div><div className="flex items-center gap-1 rounded-lg border border-border bg-card p-1"><button className={`focus-ring rounded-md p-2 ${view === 'grid' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}`} onClick={() => setView('grid')} data-testid="button-grid-view" aria-label="Grid view"><Grid2X2 size={15} /></button><button className={`focus-ring rounded-md p-2 ${view === 'list' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}`} onClick={() => setView('list')} data-testid="button-list-view" aria-label="List view"><List size={15} /></button></div></section>
    <section className="panel rounded-2xl p-3"><div className="flex flex-col gap-3 xl:flex-row"><label className="relative flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="focus-ring h-10 w-full rounded-lg border border-border bg-background pl-9 pr-3 text-xs outline-none placeholder:text-muted-foreground" placeholder="Search name, family, category, next action..." data-testid="input-project-search" /></label><div className="flex flex-wrap gap-2"><select value={family} onChange={(event) => setFamily(event.target.value)} className="focus-ring h-10 rounded-lg border border-border bg-background px-3 text-xs font-semibold outline-none" data-testid="select-family-filter"><option>All families</option>{families.map((item) => <option key={item}>{item}</option>)}</select><select value={stage} onChange={(event) => setStage(event.target.value)} className="focus-ring h-10 rounded-lg border border-border bg-background px-3 text-xs font-semibold outline-none" data-testid="select-stage-filter"><option>All stages</option>{stages.map((item) => <option key={item}>{item}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)} className="focus-ring h-10 rounded-lg border border-border bg-background px-3 text-xs font-semibold outline-none" data-testid="select-status-filter"><option>All statuses</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select><button className="focus-ring inline-flex h-10 items-center gap-2 rounded-lg border border-border px-3 text-xs font-bold text-muted-foreground hover:text-foreground" onClick={clearFilters} data-testid="button-clear-filters"><X size={14} /> Clear</button></div></div><div className="mt-3 flex flex-wrap items-center gap-2 border-t border-border pt-3"><span className="eyebrow mr-1 text-muted-foreground">Sort</span>{(['activity', 'level', 'name', 'family'] as SortKey[]).map((item) => <button key={item} className={`focus-ring rounded-full px-3 py-1.5 text-[10px] font-bold ${sort === item ? 'bg-primary text-primary-foreground' : 'bg-secondary text-muted-foreground'}`} onClick={() => setSort(item)} data-testid={`button-sort-${item}`}>{item}</button>)}<button className="focus-ring ml-auto rounded-full bg-secondary p-1.5 text-muted-foreground" onClick={() => setAscending(!ascending)} data-testid="button-sort-direction" aria-label="Toggle sort direction">{ascending ? <ArrowUpAZ size={14} /> : <ArrowDownAZ size={14} />}</button></div></section>
    {filtered.length === 0 ? <EmptyState title="No projects match these filters" description="Try widening the search or clearing one of the generated filters." /> : view === 'grid' ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((project) => <ProjectCard key={project.projectId} project={project} />)}</div> : <div className="panel overflow-hidden rounded-2xl"><div className="hidden grid-cols-[1.4fr_.9fr_.8fr_.8fr_1fr] gap-4 border-b border-border px-5 py-3 text-[10px] font-bold uppercase tracking-[.1em] text-muted-foreground md:grid"><span>Project</span><span>Family</span><span>Stage</span><span>Level</span><span>Last activity</span></div>{filtered.map((project) => <a href={`/projects/${encodeURIComponent(project.projectId)}`} className="focus-ring grid gap-2 border-b border-border px-5 py-4 last:border-0 hover:bg-secondary/45 md:grid-cols-[1.4fr_.9fr_.8fr_.8fr_1fr] md:items-center md:gap-4" key={project.projectId} data-testid={`row-project-${project.projectId}`}><div><p className="text-sm font-extrabold">{project.project}</p><p className="mt-1 font-mono-ui text-[10px] text-muted-foreground">{project.projectId}</p></div><span className="text-xs text-muted-foreground">{project.portfolioFamily}</span><span><StatusPill value={project.lifecycleStage} stage /></span><span className="text-xs font-extrabold">{project.levelPercent}%</span><span className="text-xs text-muted-foreground">{relativeDate(project.lastActivity)}</span></a>)}</div>}
  </div>;
}