import { ArrowLeft, CalendarDays, CheckCircle2, CircleAlert, ExternalLink, FileText, History, Layers3, MonitorCog } from 'lucide-react';
import { Link, useParams } from 'wouter';
import { useGetPortfolioProject, getGetPortfolioProjectQueryKey } from '@workspace/api-client-react';
import { usePortfolioContext } from '@/lib/portfolio-context';
import { ErrorState, InfoRow, LoadingState, SectionHeading, StatusPill } from '@/components/portfolio-ui';
import { formatDate, relativeDate } from '@/lib/portfolio';

export default function ProjectDetail() {
  const { projectId = '' } = useParams<{ projectId: string }>();
  const { snapshot, refresh } = usePortfolioContext();
  const cached = snapshot?.projects.find((project) => project.projectId === decodeURIComponent(projectId));
  const query = useGetPortfolioProject(decodeURIComponent(projectId), { query: { queryKey: getGetPortfolioProjectQueryKey(decodeURIComponent(projectId)), enabled: Boolean(projectId) } });
  const project = query.data || cached;
  if (query.isLoading && !cached) return <LoadingState />;
  if (query.isError || !project) return <ErrorState onRetry={() => { void query.refetch(); refresh(); }} />;
  return <div className="stagger-in space-y-8">
    <Link href="/projects" className="focus-ring inline-flex items-center gap-2 text-xs font-bold text-muted-foreground hover:text-foreground" data-testid="link-back-projects"><ArrowLeft size={14} /> All projects</Link>
    <section className="flex flex-col gap-6 border-b border-border pb-8 xl:flex-row xl:items-end xl:justify-between"><div><div><p className="eyebrow text-muted-foreground">Current Stage</p><div className="mt-2 flex flex-wrap items-center gap-2"><StatusPill value={project.lifecycleStage} stage /><StatusPill value={project.status} /></div></div><h1 className="mt-4 text-3xl font-extrabold tracking-[-0.05em] sm:text-5xl">{project.project}</h1><p className="mt-3 font-mono-ui text-[11px] text-muted-foreground">{project.projectId} · {project.portfolioFamily}{project.chatGptProjectName ? ` · ${project.chatGptProjectName}` : ''}</p></div><div className="flex items-end gap-5"><div><p className="eyebrow text-muted-foreground">Overall Project Progress</p><p className="metric-number mt-1 text-4xl font-extrabold">{project.levelPercent}%</p></div><div className="mb-2 h-2 w-36 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-accent" style={{ width: `${project.levelPercent}%` }} /></div></div></section>
      <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><div className="space-y-6"><div><SectionHeading eyebrow="Decision surface" title="What happens next" description="The smallest useful read of the project right now." /><div className="panel rounded-2xl p-5"><InfoRow label="Latest completed work" value={project.latestCompletedGate} icon={CheckCircle2} /><div className="my-3 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-primary/35 bg-primary/10 p-4"><p className="eyebrow text-primary">Current gate</p><p className="mt-2 text-sm font-bold leading-5">{project.currentGate || 'Not recorded'}</p></div><div className="rounded-xl border border-accent/35 bg-accent/10 p-4"><p className="eyebrow text-accent">Exact next action</p><p className="mt-2 text-sm font-bold leading-5">{project.exactNextAction || 'Not recorded'}</p></div></div><InfoRow label="Blocker" value={project.blocker} icon={CircleAlert} /><InfoRow label="Do not redo" value={project.doNotRedo} icon={CircleAlert} /></div></div><div><SectionHeading eyebrow="Evidence" title="Proof checkpoint" /><div className="panel rounded-2xl p-5"><div className="flex items-start gap-4"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-teal-950/60 text-teal-200"><FileText size={17} /></div><div><p className="text-sm font-extrabold">{project.evidenceCheckpoint || 'No evidence checkpoint recorded'}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{project.notes || 'No supporting notes have been added to this checkpoint.'}</p></div></div></div></div></div><div className="space-y-6"><div><SectionHeading eyebrow="Project context" title="Operating details" /><div className="panel divide-y divide-border rounded-2xl p-5"><InfoRow label="Category" value={project.category} icon={Layers3} /><InfoRow label="Product type / stack" value={project.technicalStackProductType} icon={MonitorCog} /><InfoRow label="Current work platform" value={project.currentWorkPlatform} icon={MonitorCog} /><InfoRow label="Beta status" value={project.betaStatus} icon={Layers3} /><InfoRow label="Launch status" value={project.launchStatus} icon={Layers3} /><InfoRow label="Last tracker update" value={formatDate(project.lastTrackerUpdate, true)} icon={CalendarDays} /></div></div><div><SectionHeading eyebrow="Activity" title="Latest movement" /><div className="panel rounded-2xl p-5"><div className="flex gap-3"><div className="relative flex flex-col items-center"><span className="grid size-7 place-items-center rounded-full bg-emerald-950/60 text-emerald-200"><History size={14} /></span><span className="mt-1 h-full w-px bg-border" /></div><div className="pb-2"><p className="text-xs font-bold">Tracker updated</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{project.lastActivity || 'No recent activity recorded.'}</p><p className="mt-2 font-mono-ui text-[10px] text-muted-foreground">{relativeDate(project.lastTrackerUpdate)}</p></div></div></div></div></div></section>
     <div className="flex flex-wrap items-center justify-between gap-3 border-t border-border pt-5 text-[11px] text-muted-foreground"><span>Internal founder workspace · read-only tracker view</span><span className="flex items-center gap-1.5"><ExternalLink size={12} /> Source checkpoint: {project.evidenceCheckpoint || 'unrecorded'}</span></div>
  </div>;
}