import { ArrowRight, CircleAlert, Clock3 } from 'lucide-react';
import { Link } from 'wouter';
import { usePortfolioContext } from '@/lib/portfolio-context';
import { EmptyState, ErrorState, LoadingState, SectionHeading, StatusPill } from '@/components/portfolio-ui';
import { relativeDate } from '@/lib/portfolio';

export default function Waiting() {
  const { snapshot, loading, error, refresh } = usePortfolioContext();
  const projects = (snapshot?.projects || []).filter((project) => /waiting on gate/i.test(project.status));
  if (loading) return <LoadingState />;
  if (error || !snapshot) return <ErrorState onRetry={refresh} />;
  return <div className="stagger-in space-y-8"><section><p className="eyebrow text-muted-foreground">Queue / decision required</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-0.04em] sm:text-4xl">Waiting on gate.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">These projects have reached a handoff point. Resolve the gate, or consciously leave it waiting.</p></section><div className="flex items-center gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-900"><CircleAlert size={16} /><span><strong>{projects.length} projects</strong> are paused on a gate right now.</span></div><section><SectionHeading eyebrow="Waiting queue" title="Projects needing a decision" /><div className="space-y-3">{projects.map((project) => <Link href={`/projects/${encodeURIComponent(project.projectId)}`} className="panel focus-ring group grid gap-4 rounded-2xl p-5 transition hover:border-foreground/25 md:grid-cols-[1.2fr_.9fr_1fr_auto] md:items-center" key={project.projectId} data-testid={`waiting-project-${project.projectId}`}><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-extrabold">{project.project}</p><StatusPill value={project.lifecycleStage} stage /></div><p className="mt-2 text-xs text-muted-foreground">{project.portfolioFamily} · {project.currentGate || 'Gate not named'}</p></div><div><p className="eyebrow text-muted-foreground">Blocker</p><p className="mt-1 line-clamp-2 text-xs leading-5">{project.blocker || 'No blocker recorded'}</p></div><div><p className="eyebrow text-muted-foreground">Next action</p><p className="mt-1 line-clamp-2 text-xs leading-5">{project.exactNextAction || 'No next action recorded'}</p></div><div className="flex items-center justify-between gap-3 text-muted-foreground"><span className="flex items-center gap-1.5 text-[10px]"><Clock3 size={13} />{relativeDate(project.lastActivity)}</span><ArrowRight size={15} className="transition group-hover:translate-x-1 group-hover:text-foreground" /></div></Link>)}{projects.length === 0 && <EmptyState title="No projects are waiting on a gate" description="The decision queue is clear. Keep the momentum moving." />}</div></section></div>;
}